
all : inorder postorder preorder inorder_iterative search

inorder : inorder.c
	gcc -g -o inorder inorder.c

postorder : postorder.c
	gcc -g -o postorder postorder.c

preorder : preorder.c
	gcc -g -o preorder preorder.c


inorder_iterative : inorder_iterative.c
	gcc -g -o inorder_iterative inorder_iterative.c

search : search.c
	gcc -g -o search search.c


#recursive :
#	echo "Given file runs the recursive function first"
#	sleep 1
#	echo "Inorder file"
#	./inorder
#	echo "Postorder file"
#	./postorder
#	echo "Preorder file"
#	./preorder


#iterative :
	
#	echo "Given file runs the Iterative version"
#	echo "Inorder file"
#	./inorder_iterative

