
all : stack_array stack_linked_list queue_array queue_linked_list

stack_array : stack_array.c
	gcc -g -o stack_array stack_array.c

stack_linked_list : stack_linked_list.c
	gcc -g -o stack_linked_list stack_linked_list.c

queue_array : queue_array.c
	gcc -g -o queue_array queue_array.c


queue_linked_list : queue_linked_list.c
	gcc -g -o queue_linked_list queue_linked_list.c

s_a :
	echo " Demonstrating stack array version "
	./stack_array

s_ll :
	echo " Demonstrating stack linked list version "
	./stack_linked_list

q_a :
	echo " Demonstrating queue array version "
	./queue_array

q_ll :
	echo " Demonstrating queue linked list version "
	./queue_linked_list

